//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace LiveShot.API.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("LiveShot.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.Canvas.Tooltip.
        /// </summary>
        public static string CaptureScreen_Canvas_Tooltip {
            get {
                return ResourceManager.GetString("CaptureScreen.Canvas.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Arrow.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Arrow {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Close.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Close {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.ColorPicker.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_ColorPicker {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Copy.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Copy {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.EyeDropper.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_EyeDropper {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.EyeDropper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Google.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Google {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Highlighter.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Highlighter {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Highlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Pencil.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Pencil {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Pencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Print.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Print {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Rectangle.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Rectangle {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Save.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Save {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Share.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Share {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CaptureScreen.CanvasButtons.Stroke.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Stroke {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Stroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Text.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Text {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Undo.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Undo {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.CanvasButtons.Upload.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Upload {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.SaveImage.FileName.
        /// </summary>
        public static string CaptureScreen_SaveImage_FileName {
            get {
                return ResourceManager.GetString("CaptureScreen.SaveImage.FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.SaveImage.Title.
        /// </summary>
        public static string CaptureScreen_SaveImage_Title {
            get {
                return ResourceManager.GetString("CaptureScreen.SaveImage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.SizeLabel.Empty.
        /// </summary>
        public static string CaptureScreen_SizeLabel_Empty {
            get {
                return ResourceManager.GetString("CaptureScreen.SizeLabel.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureScreen.Title.
        /// </summary>
        public static string CaptureScreen_Title {
            get {
                return ResourceManager.GetString("CaptureScreen.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.Message.
        /// </summary>
        public static string Exception_Message {
            get {
                return ResourceManager.GetString("Exception.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportWindow.Copy.
        /// </summary>
        public static string ExportWindow_Copy {
            get {
                return ResourceManager.GetString("ExportWindow.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportWindow.Open.
        /// </summary>
        public static string ExportWindow_Open {
            get {
                return ResourceManager.GetString("ExportWindow.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportWindow.Title.
        /// </summary>
        public static string ExportWindow_Title {
            get {
                return ResourceManager.GetString("ExportWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imgur.InvalidClientIdException.
        /// </summary>
        public static string Imgur_InvalidClientIdException {
            get {
                return ResourceManager.GetString("Imgur.InvalidClientIdException", resourceCulture);
            }
        }
    }
}
