//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveShot.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveShot.API.Properties.Resources.en-US", typeof(Resources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot {0:dd-MM-yyyy HH mm}.
        /// </summary>
        public static string CaptureScreen_SaveImage_FileName {
            get {
                return ResourceManager.GetString("CaptureScreen.SaveImage.FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image.
        /// </summary>
        public static string CaptureScreen_SaveImage_Title {
            get {
                return ResourceManager.GetString("CaptureScreen.SaveImage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty selection.
        /// </summary>
        public static string CaptureScreen_SizeLabel_Empty {
            get {
                return ResourceManager.GetString("CaptureScreen.SizeLabel.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Exception_Message {
            get {
                return ResourceManager.GetString("Exception.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ExportWindow_Copy {
            get {
                return ResourceManager.GetString("ExportWindow.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ExportWindow_Open {
            get {
                return ResourceManager.GetString("ExportWindow.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export screenshot.
        /// </summary>
        public static string ExportWindow_Title {
            get {
                return ResourceManager.GetString("ExportWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client ID for imgur API.
        /// </summary>
        public static string Imgur_InvalidClientIdException {
            get {
                return ResourceManager.GetString("Imgur.InvalidClientIdException", resourceCulture);
            }
        }
    }
}
